### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by affkie** [belowaverage-org/SuperUpdate#10]
SuperUpdate program says no internet but connection is stable. Please tell me how to solve this problem. Thanks in advance.

**Comment by krisdb2009** [comment]
That error will appear if you don't have a connection to this GitHub repository. (That is where USMT is downloaded from initially)

You can manually copy USMT into a folder yourself and point Super Grate at it by adjusting the USMTPathX64 setting in the settings menu.

![image](https://user-images.githubusercontent.com/8226974/204873604-e410d191-0fee-4792-a669-5db5f6afe9e9.png)

So just to re-cap, download this ZIP file containing USMT https://github.com/belowaverage-org/SuperGrate/blob/master/USMT/x64.zip

Extract it to a folder of your choice, and change the setting described above to point at the extracted folder.

Let me know if this works!
